name: Test and Build a Go Project ...

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
            path: ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ${{ runner.os }}-go-
      - name: Intall SQLite3
        run: sudp apt-get update && sudo apt-get install -y sqlite3 libsqlite3-dev

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Run the tests
        run: go test -v ./...
        env:
          DATABASE_URL: "test.db"

